#!/usr/bin/env bash
#random bash script

if [ $# -lt 2 ]; then
	domainlist=(www lb-01 web-01 web-02)
	for i in {0..3}; do
		domainhost=$(dig "${domainlist[i]}.$1" +short)
		if [ -n "$domainhost" ]; then
    			echo "The subdomain ${domainlist[i]} is a A record and points to $domainhost"
		fi
	done
else
	domainhost=$(dig "$2.$1" +short)
	if [ -n "$domainhost" ]; then
		echo "The subdomain $2 is a A record and points to $domainhost"
	fi
fi
