#!/usr/bin/env bash
#saving the world again

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]; then
	scp StrictHostKeyChecking=no "$1" "$3"@"$2":~/
else
	scp StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
