#!/usr/bin/env bash
#saving the world again

sudo su
#the task
apt-get update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i 'listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/custom404.html
sed -i "error_page 404 /custom404.html;" /etc/nginx/sites-available/default
service nginx start
