#!/usr/bin/env bash
#saving the world again

sudo su
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
sed -i '25i rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "46i error_page 404 /404.html;" /etc/nginx/sites-available/default
sed -i "49i add_header X-Served-By $hostname;" /etc/nginx/sites-available/default
service nginx start
