#!/usr/bin/env bash
#saving the world again

sudo su
apt-get update -y
apt-get upgrade -y
apt-get install -y haproxy
cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
cat <<EOF > /etc/haproxy/haproxy.cfg
frontend main
        bind *:80
        timeout client 10s
        default_backend main
backend main
	balance roundrobin
        timeout server 10s
        timeout connect 10s
        server web-01 34.224.2.46:80
        server web-02 34.204.60.68:80
EOF
service haproxy restart
