#!/usr/bin/env bash
#saving the world again

cat <<EOF > conf.cfg
frontend main
        bind *:80
        timeout client 10s
        default_backend main
backend main
        timeout server 10s
        timeout connect 10s
        server web-01 34.224.2.46:80
        server web-02 34.204.60.68:80
EOF
sudo haproxy -f conf.cfg
