#!/usr/bin/env bash
# this code is also doing something

trap "echo 'I hate the kill command' && rm /var/run/myscript.pid" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid" SIGQUIT

touch /var/run/myscript.pid
echo pgrep -f "myscript.pid" >> /var/run/myscript.pid

while true
do
	echo "To infinity and beyond"
	sleep 2
done
