#!/usr/bin/env bash
#this script is doing something

i=0
while [ "$i" -lt 10 ]
do
	(( i++ ))
	if [ $i -eq 8 ]
	then
		echo "good luck"
		continue
	elif [ $i -eq 4 ]
	then
		echo "good luck"
		continue
	fi
	echo "Best School"
done
