#!/usr/bin/env bash
#this script is doing something

cp /etc/hosts ~/hosts.new
sed -i 's/^127[0-9.]*\slocalhost/127.0.0.2 localhost/g' ~/hosts.new
echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
